substitutions:
  name: bedroom-heat-pump
  area: Bedroom
  encryption_key: !secret bedroom-heat-pump_encryption_key
  ota_password: !secret bedroom-heat-pump_ota_password
  sources:
    - external_temperature

packages:
  base: !include packages/heat-pump/base.yaml
  net: !include packages/heat-pump/net-wifi.yaml
  external_temperature: !include
    file: packages/heat-pump/source-config.yaml
    vars:
      source:
        name: "Bedroom"
        internal_id: external_temperature
        entity_id: sensor.bedroom_sensor_temperature

