substitutions:
  name: bedroom-heat-pump
  area: Bedroom
  encryption_key: !secret bedroom-heat-pump_encryption_key
  ota_password: !secret bedroom-heat-pump_ota_password

packages:
  base: !include packages/heat-pump/base.yaml
  net: !include packages/heat-pump/net-wifi.yaml
  source: !include packages/heat-pump/source-internal.yaml

