substitutions:
  name: workshop-heat-pump
  area: Workshop
  encryption_key: !secret workshop-heat-pump_encryption_key
  ota_password: !secret workshop-heat-pump_ota_password
  sources:
    - external_temperature

packages:
  base: !include packages/heat-pump/base.yaml
  net: !include packages/heat-pump/net-wifi.yaml
  external_temperature: !include
    file: packages/heat-pump/source-config.yaml
    vars:
      source:
        name: "Workshop"
        internal_id: external_temperature
        entity_id: sensor.workshop_sensor_temperature

