substitutions:
  name: nursery-heat-pump
  area: Nursery
  encryption_key: !secret nursery-heat-pump_encryption_key
  ota_password: !secret nursery-heat-pump_ota_password

packages:
  base: !include packages/heat-pump/base.yaml
  net: !include packages/heat-pump/net-wifi.yaml
  source: !include packages/heat-pump/source-internal.yaml
