substitutions:
  name: "REQUIRED"
  friendly_name: "REQUIRED"
  log_level: INFO
  device_description: "Athom Garage Door Opener"
  project_name: "China Athom Technology.Garage Door Opener"
  project_version: "v3.1.1"
  sntp_update_interval: 6h
  sntp_server_1: "0.pool.ntp.org"
  sntp_server_2: "1.pool.ntp.org"
  sntp_server_3: "2.pool.ntp.org"    

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "${device_description}"
  area: "Garage"
  min_version: 2025.11.0
  project:
    name: "${project_name}"
    version: "${project_version}"
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  variant: ESP32C3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

api:
  encryption:
    key: !secret garage-door_encryption_key
  # reboot_timeout: 0s
  # Only enable BLE tracking when wifi is up and api is connected
  # Gives single-core ESP32-C3 devices time to manage wifi and authenticate with api
  on_client_connected:
     - esp32_ble_tracker.start_scan:
        continuous: true
  # Disable BLE tracking when there are no api connections live
  on_client_disconnected:
    if:
      condition:
        not:
          api.connected:
      then:
        - esp32_ble_tracker.stop_scan:

ota:
  - platform: esphome
    password: !secret garage-door_ota_password

logger:
  baud_rate: 0  # 0 Enables logging, but disables serial-port logging to free CPU and memory
  level: ${log_level}
  hardware_uart: UART0

mdns:
  disabled: false

web_server:
  port: 80

network:
  enable_ipv6: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  fast_connect: false
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret ap_fallback_password

captive_portal:

esp32_improv:
  authorizer: none

esp32_ble_tracker:
  scan_parameters:
    # Don't auto start BLE scanning, we control it in the `api` block's automation.
    continuous: false
    active: true  # send scan-request packets to gather more info, like device name for some devices.
    interval: 320ms  # default 320ms - how long to spend on each advert channel
    window:   300ms  # default 30ms - how long to actually "listen" in each interval. Reduce this if device is unstable.
    # If the device cannot keep up or becomes unstable, reduce the "window" setting. This may be
    # required if your device is controlling other sensors or doing PWM for lights etc.

bluetooth_proxy:
  active: true

dashboard_import:
  package_import_url: github://athom-tech/esp32-configs/athom-garage-door.yaml

sensor:
  - platform: uptime
    name: "Uptime Sensor"
    id: uptime_sensor
    type:
      timestamp
    entity_category: "diagnostic"

  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

binary_sensor:
  - platform: status
    name: "Status"

  - platform: gpio
    name: "Contact"
    disabled_by_default: true
    device_class: garage_door
    id: contact
    pin:
      number: GPIO18
      inverted: true
    filters:
      - delayed_on: 20ms

  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    name: "Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.turn_on: relay
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

button:
  - platform: restart
    name: "Restart"
    entity_category: config

  - platform: factory_reset
    name: "Factory Reset"
    id: Reset
    entity_category: config

  - platform: safe_mode
    name: "Safe Mode"
    internal: false
    entity_category: config

switch:
  - platform: gpio
    pin: GPIO7
    name: "Relay"
    id: relay
    disabled_by_default: true
    on_turn_on:
      - light.turn_on: wifi_led
      - delay: 1s
      - switch.turn_off: relay
      - light.turn_off: wifi_led

light:
  - platform: status_led
    name: "Status LED"
    id: wifi_led
    disabled_by_default: true
    pin: GPIO4

cover:
  - platform: template
    device_class: garage
    name: "Garage Door"
    lambda: "return id(contact).state ? COVER_OPEN : COVER_CLOSED;"
    open_action:
      then:
       - if:
          condition:
            lambda: 'return !id(contact).state;'
          then:
              - switch.turn_on: relay
    stop_action:
      - switch.turn_on: relay
    close_action:
      then:
       - if:
          condition:
            lambda: 'return id(contact).state;'
          then:
            - switch.turn_on: relay

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      entity_category: diagnostic
    mac_address:
      name: "Mac Address"
      entity_category: diagnostic

  - platform: template
    name: 'Last Restart'
    id: device_last_restart
    icon: mdi:clock
    entity_category: diagnostic
    device_class: timestamp

time:
  - platform: sntp
    id: sntp_time
    update_interval: ${sntp_update_interval}
    servers: 
      - "${sntp_server_1}"
      - "${sntp_server_2}"
      - "${sntp_server_3}"   
  # Publish the time the device was last restarted
    on_time_sync:
      then:
        # Update last restart time, but only once.
        - if:
            condition:
              lambda: 'return id(device_last_restart).state == "";'
            then:
              - text_sensor.template.publish:
                  id: device_last_restart
                  state: !lambda 'return id(sntp_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'
